version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: test_laravel
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  laravel:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./:/app

volumes:
  postgres_data:
