version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: test_laravel         # Имя базы данных, которую нужно создать
      POSTGRES_USER: krtv           # Имя пользователя для доступа к базе данных
      POSTGRES_PASSWORD: 6552    # Пароль для пользователя
    ports:
      - "5432:5432"                    # Проброс порта
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Хранение данных

volumes:
  postgres_data:
